export  const data = [
    {
        id:1,
        title:'Guitars',
        img:'Images/Guitar_bw.jpeg'
    },
    {
        id:2,
        title:'Guitars',
        img:'Images/Piano_bw.jpeg'
    },
    {
        id:3,
        title:'Guitars',
        img:'Images/Notes_bw.jpeg'
    },
    {
        id:4,
        title:'Guitars',
        img:'Images/background_Drums.jpeg'
    },
    {
        id:5,
        title:'Guitars',
        img:'Images/Vocals_bw.jpeg'
    },
    {
        id:6,
        title:'Guitars',
        img:'Images/Ukulele_bw.jpeg'
    },
    {
        id:7,
        title:'Guitars',
        img:'Images/Tabla_bw.jpeg'
    },
    {
        id:8,
        title:'Guitars',
        img:'Images/Vocals2_bw.jpeg'
    },
    {
        id:9,
        title:'Guitars',
        img:'Images/Vocals3_bw.jpeg'
    },
]
