export const data = [
    {
        id: 1,
        title: 'Gulistaan',
        img: 'Images/Vocals2_bw.jpg',
        content: 'Ooooo...we have got something very intersting for our little rockstars! Read on to find out more about this unique program of ours!',
        content2:'This program is specifically designed for children between 3 & 6 years. At this young age, kids arent aware of their interest points and neither are the parents. So, we get them together, sing, dance & play music, keeping the musical instruments & emphasis on vocals as a central theme. This way, they experience each instrument one by one and spend quality time getting familiar! ',
        courseFirstPageImg: 'Images/Vocals2_bw.jpg',
        footerImg: 'Images/Vocals2_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-los-angeles-ca-december-tcl-chinese-theatre-where-actor-ben-stiller-had-his-hand-footprints-set-cement-45634142.jpg',
        secondPageContentTopRed:'Start them young!',
        secondPageContentTopBlack:'and give them an opportunity to explore!',
        secondPageContentMiddle:'...says our co-founder Ms. Ashita K Sharma who is the curator of "Gulistaan". She conducts each session herself & ensures that every child gets a chance to explore his or her interest. The parents are also invited to attend some of the sessions & they take the journey along with their little ones!' ,
        secondPageContentBottom:'“A child’s mind is not a container to be filled but rather a fire to be kindled.” – Dorothea Brande.',
        scheduleCardImg1:'Images/Vocals2_bw.jpg',
        scheduleCardImg2:'Images/Vocals2_bw.jpg',
        scheduleCardImg3:'Images/Vocals2_bw.jpg',
        firstDivContentH:'Age Group',
        firstDivContentP:'Kids between 3 & 6 yrs are welcome to join this session. For each batch we take a maximum of 5 kids. The duration of the course is anywhere from 1 to 2 months depending on how quickly each child takes to their liking for an instrument or for vocals.',
        secondDivContentH:'Progression',
        secondDivContentP:'Once a child is comfortable with an instrument and shows inclination towards it, the child is moved to that instrument"s batch and they continue their journey of learning from the respective teacher!',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Gulistaan session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 2,
        img: 'Images/Guitar_bw.jpeg',
        title: 'Guitar',
        footerImg: 'Images/Guitar_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/scarlett-johansson-25269945.jpg',
        content: 'Learn the most popular instrument that is sure to make you "Popular".',
        content2:'Most of us, young or old, have at least once thought of playing or learning this super attractive instrument. Learning to play a Guitar requires the right amount of patience, right technique & most importantly a right teacher. Its not only about playing chords but about getting into the skin of the instrument & playing it at will!',
        courseFirstPageImg: 'Images/Guitar_bw.jpeg',
        secondPageContentTopRed:'It might take time...',
        secondPageContentTopBlack:'but learn it right.',
        secondPageContentMiddle:'Mr. Jai Chauhan has been with us since the academy"s inception. A Delhi School of Music passout, Trinity Grade 8 certified & a magician on the fret, Jai brings life to the instrument the moment he touches it! His lessons are targeted towards listening & playing that makes the students independent & gives them an opportunity to experiment!',
        secondPageContentBottom:'“My guitar is not a thing. It is an extension of myself. It is who I am.” - Joan Jett.',
        scheduleCardImg1:'Images/Guitar_bw.jpeg',
        scheduleCardImg2:'Images/Guitar_bw.jpeg',
        scheduleCardImg3:'Images/Guitar_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'While there is no such rule, but a good age to start learing guitar is 6 yrs. By this time, the fingers are strong enough to work on the Guitar"s fret. There is no upper age limit of course, as long as you feel it in your heart, you can learn to play the Guitar!',
        secondDivContentH:'Progression',
        secondDivContentP:'From finding notes on the fret, to learning about scales, chords & melodies, the curve while learning a guitar is quite a big one. Yes, it requires practice but once you start getting the hang of it, you just wont feel like putting it down!',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Guitar session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 3,
        title: 'Keyboard',
        img: 'Images/Piano_bw.jpeg',
        content: 'An excellent instrument to start with for all age groups!',
        content2:'A Keyboard is a beginner friendly instrument and it is relatively easy to play. It requires minimal physical effort thereby making it a popular choice to start with amongst kids & adults alike.' ,
        courseFirstPageImg: 'Images/Piano_bw.jpeg',
        footerImg: 'Images/Piano_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-actor-world-premiere-hollywood-his-new-movie-vanilla-sky-dec-paul-smith-featureflash-36734471.jpg',
        secondPageContentTopRed:'The Key to learn quickly..',
        secondPageContentTopBlack:'..is to practice, practice & practice!',
        secondPageContentMiddle:'Keyboard is a preferred choice for all age groups. That is why Mr. Gaurav Mehra, our Keyboard teacher is a hot favorite amongst both kids & adults. His teaching methods are simple & are quick to absorbe. He hails from a family of great musicians & is trained in both classical & western music. He ensures that his students learn the staff notations as well as they learn to reproduce their favorite songs on the Keyboard.',
        secondPageContentBottom:'“One of the biggest thrills for me still is sitting down with a piano & just out of nowhere, trying to make a song happen.” – Paul McCartney.',
        scheduleCardImg1:'Images/Piano_bw.jpeg',
        scheduleCardImg2:'Images/Piano_bw.jpeg',
        scheduleCardImg3:'Images/Piano_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'Kids as young as 4 yrs can start learning the keyboard. There is ofcourse, no upper age limit to start learning this wonderful instrument. Most of our batches for Keyboard have students from all age groups learning together.',
        secondDivContentH:'Progression',
        secondDivContentP:'Students start by learning to play with one hand & then quickly move on to playing with both. We focus heavily on "ear training" while teaching how to play the keyboard. Our aim is to enable the student to listen to a song or a melody & then reproduce it on the Keyboard.',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Keyboard session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 4,
        title: 'Drums',
        img: 'Images/background_Drums.jpeg',
        content: 'The best instrument to channelise your energy & to unleash your inner power!',
        content2: 'The Backbone of a band. The Timekeeper. The Rythm generator. Apart from "Drums", there are many names that this magnificent instrument is known by. Beign an instrument that requires the student to learn "Limb independence", its a joy to go throught the journey of learning & mastering the kit!',
        courseFirstPageImg: 'Images/background_Drums.jpeg',
        footerImg: 'Images/background_Drums.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/scarlett-johansson-20484293.jpg',
        secondPageContentTopRed:'First you learn on the practice pad..',
        secondPageContentTopBlack:'..only then can you kill it on the kit.',
        secondPageContentMiddle:'Ojas might be the youngest member of our squad but he is one of the most technically sound teachers that we have. His belief is simple - unless you have broken a few practice pads, you wont be able to kill it on the drum kit. His students adore him as he gets their fundamentals so strong that they can play any rythm, any song, any melody with utmost confidence & precision!',
        secondPageContentBottom:'“You only get better by playing. If you think you stink, you probably do. I consider every drummer that ever played before me an influence, in every way.” – Buddy Rich.',
        scheduleCardImg1:'Images/background_Drums.jpeg',
        scheduleCardImg2:'Images/background_Drums.jpeg',
        scheduleCardImg3:'Images/background_Drums.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'4-5 yrs is a good age for kids to start learning. Adults can start anytime they feel the kick to do so. But Drums require physical strenght & energy to play, so the sooner you start, the better it is!',
        secondDivContentH:'Progression',
        secondDivContentP:'One needs to spend a considerable time mastering the patterns, time signatures & building the rythm sense that is required to play the Drums. However, it all comes easy, if your heart & mind are into it!',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Drums session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 5,
        title: 'Vocals',
        img: 'Images/Vocals_bw.jpeg',
        content: 'Learn to sing like the rain, develope your vocal range & charm everyone around!',
        content2:'Arent we all bathroom singers? Or snatching the mic at a karaoke party to show our singing talents? Well, with our carefully carfted vocals module, you can graduate from a bathroom singer to the one who hits all the right notes! One of our most popular courses, learing vocals with us will give wings to your voice & make you the life of every party!',
        courseFirstPageImg: 'Images/Vocals_bw.jpeg',
        footerImg: 'Images/Vocals_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-26359187.jpg',
        secondPageContentTopRed:'Sing like no one is watching..',
        secondPageContentTopBlack:'..and you will discover how to sing effortlessly!',
        secondPageContentMiddle:'Our allrounder - Mr. Gaurav Mehra takes it upon himself to ensure that you do your riyaz & come prepared for every session. Weather its hindustani classical, semi classical or western singing, he is sure to bring the best out of you & make you sing the tougest of songs with greatest of ease!',
        secondPageContentBottom:'“God respects me when I work, but he loves me when I sing.”- Rabindranath Tagore.',
        scheduleCardImg1:'Images/Vocals_bw.jpeg',
        scheduleCardImg2:'Images/Vocals_bw.jpeg',
        scheduleCardImg3:'Images/Vocals_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'There is literally no age to start learning to sing! Its a trainable skill & with the right guidence, anyone can sing beautifully! Our batches for vocals are made up of students from all age groups & from all walks of life!',
        secondDivContentH:'Progression',
        secondDivContentP:'We start with absolute basics & teach students about sur, raag, alankars & other technicalities that help them understand the composition of a song. Each session has some or the other elements of theory that helps them correct & better their course!',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Vocals session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 6,
        title: 'Ukulele',
        img: 'Images/Ukulele_bw.jpeg',
        content: 'Slowly becoming one of the most liked instrument worldwide, Ukulele is easy to learn & fun to play!',
        content2:'Ukulele is played just like the guitar but it only has 4 strings. Its also smaller in size & has more rythemic elements to it. Weather its a rainy day or a casual get together, there is never a bad time to pick up a Ukelele & start strumming it!',
        courseFirstPageImg: 'Images/Ukulele_bw.jpeg',
        footerImg: 'Images/Ukulele_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-arrives-jack-reacher-premiere-odeon-leicester-square-london-picture-steve-vas-featureflash-30288885.jpg',
        secondPageContentTopRed:'It might be small..',
        secondPageContentTopBlack:'but it needs the same amount of dedication!',
        secondPageContentMiddle:'Mr. Jai Chauhan teaches Ukulele at our academy & he takes his students through the beautiful, rhytmic journey of learning. Being skilled at flamenco strumming, Jai handles the Ukulele as its a part of his soul & his students can almost always feel that connection!',
        secondPageContentBottom:'Sometimes I can’t think of a better way to end my day than coming home and just strumming my ukulele for a few minutes. I mean, I joke around and tell people that it’s an entire yoga session in one strum, you know? – Jake Shimabukuro.',
        scheduleCardImg1:'Images/Ukulele_bw.jpeg',
        scheduleCardImg2:'Images/Ukulele_bw.jpeg',
        scheduleCardImg3:'Images/Ukulele_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'As its small & easy to handle, kids as young as 5 yrs can start learning. Though many adults in their late 40s have started to take a liking towards Ukelele & we cant be more happy about it!',
        secondDivContentH:'Progression',
        secondDivContentP:'Just like learning any string instrument, there is considerable amount of finger strength & dexterity required. But with right guidance, a helpful teacher & a little bit of patience, you can quickly learn to strum some of your favorite melodies!',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Ukulele session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 7,
        title: 'Tabla',
        img: 'Images/Tabla_bw.jpeg',
        content: 'And yes! We teach indian classical instruments too! The key to master it is to start learning at an early age! ',
        content2:'Since the 18th century, Tabla has been the principal percussion instrument in Hindustani classical music. However, recently it has been a part of many fusion based songs where it blends amazingly well with other western instruments.',
        courseFirstPageImg: 'Images/Tabla_bw.jpeg',
        footerImg: 'Images/Tabla_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/katie-holmes-tom-cruise-kennedy-26357184.jpg',
        secondPageContentTopRed:'Your hands do the work..',
        secondPageContentTopBlack:'..but the magic happens in your heart!',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Tabla_bw.jpeg',
        scheduleCardImg2:'Images/Tabla_bw.jpeg',
        scheduleCardImg3:'Images/Tabla_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'Learning to play Table requires skills & hand eye coordination, which is better developed at an early age. A lot of students start as early at 4 yrs & continue their learning journey throughout. Ofcourse, adults with great control on their hands & fingers should also give it a shot!',
        secondDivContentH:'Progression',
        secondDivContentP:'',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each Tabla session comprises of 8 classes (02 classes every week of 01 hour each). The fee is payable at the beginnig of each session. Group & Individual sessions are available.'
    },
    {
        id: 8,
        title: 'Trinity & Rock School',
        img: 'Images/Notes_bw.jpeg',
        content: 'We teach sheet music & prepare our students for Indian & International exams for all instruments (that we teach).',
        content2:'We arent just a hobby school & its our aim to provide quality music education to each of our students. Therefore, we not only teach curriculums from these prestigious international schools but we also help the students take these exams & clear them with flying colors!',
        courseFirstPageImg: 'Images/Notes_bw.jpeg',
        footerImg: 'Images/Notes_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-12923562.jpg',
        secondPageContentTopRed:'Theory isnt boring..',
        secondPageContentTopBlack:'..it actually makes playing more intersting!',
        secondPageContentMiddle:'Trinity & Rock School curriculum is world respected & all our teachers are well equipped to coach & prepare students for these examinations. The sessions for these are separetly held & only students preparing for these exams are a part of such sessions. We do not conduct these examinations but only prepare students to take them.',
        secondPageContentBottom:'"Theory and harmony broadened my mind in music. I know what music is made of - Nina Simone"',
        scheduleCardImg1:'Images/Notes_bw.jpeg',
        scheduleCardImg2:'Images/Notes_bw.jpeg',
        scheduleCardImg3:'Images/Notes_bw.jpeg',
        firstDivContentH:'Age Group',
        firstDivContentP:'One can start at any age as long as you can read & write! Its however, better to have a few months of experience of playing the instrument for which you would like to persue taking grade examinations.',
        secondDivContentH:'Progression',
        secondDivContentP:'There are usually 6- 8 grades for most western instruments. It can take anywhere between 4-6 years clearing all but then it all really depends on the student"s dedication & discipline to learn.',
        thirdDivContentH:'Commercials',
        thirdDivContentP:'Each grade has a progressive difficulty level. We charge INR 4800 to teach Grade 1-3, 6400 for Grade 4-6 & 1000 for Grade 7-8. Group & Individual sessions are available.'
    },
    {
        id: 9,
        title: 'Misc',
        img: 'Images/Vocals3_bw.jpeg',
        content: 'there should be the content',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Vocals3_bw.jpeg',
        footerImg: 'Images/Vocals3_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-los-angeles-ca-december-tcl-chinese-theatre-where-actor-ben-stiller-had-his-hand-footprints-set-cement-45634142.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Vocals3_bw.jpeg',
        scheduleCardImg2:'Images/Vocals3_bw.jpeg',
        scheduleCardImg3:'Images/Vocals3_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'

    },
]
