export const data = [
    {
        id: 1,
        title: 'Gulistaan',
        img: 'Images/Vocals2_bw.jpg',
        content: 'Ooooo...we have got something very intersting for our little rockstars! Read on to find out more about this unique program of ours!',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Vocals2_bw.jpeg',
        footerImg: 'Images/Vocals2_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-los-angeles-ca-december-tcl-chinese-theatre-where-actor-ben-stiller-had-his-hand-footprints-set-cement-45634142.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Vocals2_bw.jpeg',
        scheduleCardImg2:'Images/Vocals2_bw.jpeg',
        scheduleCardImg3:'Images/Vocals2_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 2,
        img: 'Images/Guitar_bw.jpeg',
        title: 'Guitar',
        footerImg: 'Images/Guitar_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/scarlett-johansson-25269945.jpg',
        content: 'Learn the most popular instrument that is sure to make you "Popular".',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Guitar_bw.jpeg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Guitar_bw.jpeg',
        scheduleCardImg2:'Images/Guitar_bw.jpeg',
        scheduleCardImg3:'Images/Guitar_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 3,
        title: 'Keyboard',
        img: 'Images/Piano_bw.jpeg',
        content: 'An excellent instrument to start with for all age groups!',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Piano_bw.jpeg',
        footerImg: 'Images/Piano_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-actor-world-premiere-hollywood-his-new-movie-vanilla-sky-dec-paul-smith-featureflash-36734471.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Piano_bw.jpeg',
        scheduleCardImg2:'Images/Piano_bw.jpeg',
        scheduleCardImg3:'Images/Piano_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 4,
        title: 'Drums',
        img: 'Images/background_Drums.jpeg',
        content: 'The best instrument to channelise your energy & unleash your inner power!',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/background_Drums.jpeg',
        footerImg: 'Images/background_Drums.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/scarlett-johansson-20484293.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/background_Drums.jpeg',
        scheduleCardImg2:'Images/background_Drums.jpeg',
        scheduleCardImg3:'Images/background_Drums.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
        
    },
    {
        id: 5,
        title: 'Vocals',
        img: 'Images/Vocals_bw.jpeg',
        content: 'Learn to sing like the rain, develope your vocal range & charm everyone around!',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Vocals_bw.jpeg',
        footerImg: 'Images/Vocals_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-26359187.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Vocals_bw.jpeg',
        scheduleCardImg2:'Images/Vocals_bw.jpeg',
        scheduleCardImg3:'Images/Vocals_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
        
    },
    {
        id: 6,
        title: 'Ukulele',
        img: 'Images/Ukulele_bw.jpeg',
        content: 'Slowly becoming one of the most liked instrument worldwide, Ukulele is easy to learn & fun to play!',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Ukulele_bw.jpeg',
        footerImg: 'Images/Ukulele_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-arrives-jack-reacher-premiere-odeon-leicester-square-london-picture-steve-vas-featureflash-30288885.jpg',
        
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Ukulele_bw.jpeg',
        scheduleCardImg2:'Images/Ukulele_bw.jpeg',
        scheduleCardImg3:'Images/Ukulele_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 7,
        title: 'Tabla',
        img: 'Images/Tabla_bw.jpeg',
        content: 'And yes! We teach indian classical instruments too! The key to master it is to start learning at an early age! ',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Tabla_bw.jpeg',
        footerImg: 'Images/Tabla_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/katie-holmes-tom-cruise-kennedy-26357184.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Tabla_bw.jpeg',
        
        scheduleCardImg2:'Images/Tabla_bw.jpeg',
        scheduleCardImg3:'Images/Tabla_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 8,
        title: 'Trinity & Rock School',
        img: 'Images/Notes_bw.jpeg',
        content: 'We teach sheet music & prepare our students for Indian & International exams for all instruments that we teach.',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Notes_bw.jpeg',
        footerImg: 'Images/Notes_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-12923562.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Notes_bw.jpeg',
        scheduleCardImg2:'Images/Notes_bw.jpeg',
        scheduleCardImg3:'Images/Notes_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'
    },
    {
        id: 9,
        title: 'Misc',
        img: 'Images/Vocals3_bw.jpeg',
        content: 'there should be the content',
        content2:'this is  dynamic data for the second page',
        courseFirstPageImg: 'Images/Vocals3_bw.jpeg',
        footerImg: 'Images/Vocals3_bw.jpeg',
        courseSecondPageImg:'https://thumbs.dreamstime.com/b/tom-cruise-los-angeles-ca-december-tcl-chinese-theatre-where-actor-ben-stiller-had-his-hand-footprints-set-cement-45634142.jpg',
        secondPageContentTopRed:'Programs for every',
        secondPageContentTopBlack:'level and need',
        secondPageContentMiddle:'The Missing Note successfully raises the bar on music education, with a commitment to excellence, and a mission to help both music majors and non-music majors reach their creative potential. School period of music studies which can be 2 years for deep skills.',
        secondPageContentBottom:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X.',
        scheduleCardImg1:'Images/Vocals3_bw.jpeg',        
        scheduleCardImg2:'Images/Vocals3_bw.jpeg',
        scheduleCardImg3:'Images/Vocals3_bw.jpeg',
        firstDivContentH:'Students',
        firstDivContentP:'Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional.',
        secondDivContentH:'Levels',
        secondDivContentP:'Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal.',
        thirdDivContentH:'CERTIFICATE',
        thirdDivContentP:'Leverage agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster.'

    },
]
